services:
  http:
    container_name: email_generator
    image: nginx
    networks:
      - email_generator_default
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf/dev/nginx.dev.conf:/etc/nginx/conf.d/default.conf

  app:
    container_name: email_generator_app
    build:
      context: docker/app
      dockerfile: Dockerfile
    networks:
      - email_generator_default
    volumes:
      - .:/var/www
      - ./docker/app/conf/php.ini:/usr/local/etc/php/php.ini
      - ./docker/app/conf/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini

networks:
  email_generator_default:
